/**
 * Writes the upload spec's fixtures into this directory.
 *
 * **These are generated, not photographs.** Every image is flat colour and
 * a few shapes drawn by ImageMagick, and every video is FFmpeg's own test
 * pattern. Nothing here was taken by a camera, and nothing here may be: the
 * repository is public, and `.gitignore` refuses every photo and video format
 * outside this one directory.
 *
 * Each file exists for one thing the upload path has to get right:
 *
 * | File                         | What it proves                                    |
 * | ---------------------------- | ------------------------------------------------- |
 * | `portrait-orientation-6.jpg` | EXIF rotation, and rung 1 with an offset          |
 * | `heic-rotated.heic`          | HEIC in both engines, `irot`, rung 1 and no offset |
 * | `IMG-20260503-WA0001.jpg`    | No EXIF at all: rung 3, the filename              |
 * | `h264-clip.mp4`              | H.264 and rung 2; the base of the multipart file  |
 * | `hevc-clip.mov`              | HEVC in QuickTime, as a phone records, and rung 2 |
 * | `not-media.pdf`              | A type the manifest refuses before a byte moves   |
 *
 * The three photographs are larger than the 2048 px display size on purpose,
 * so that both derivatives are real downscales and the spec can assert their
 * sizes. The file large enough to go multipart is not here: the threshold is
 * 32 MiB, too big to commit, so `e2e/support/uploadHarness.ts` writes it at
 * run time from `h264-clip.mp4`.
 *
 * Run it on a Mac, from the repository root, only when a fixture has to
 * change, and commit what it writes:
 *
 * ```sh
 * node e2e/fixtures/upload/makeUploadFixtures.ts
 * ```
 *
 * It needs `magick` (ImageMagick 7), `ffmpeg` with libx264 and libx265, and
 * macOS's own `sips`, which encodes the HEIC: Apple's encoder writes the
 * container an iPhone does, `irot` and EXIF orientation together, and `exifr`
 * reads that container's EXIF where it cannot read libheif's. No EXIF tool is
 * needed, because the EXIF block is written below byte by byte. The output is
 * not byte-identical across tool versions, which is why it is committed rather
 * than generated by the run.
 */
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

/** This directory, which is where every fixture is written. */
const FIXTURE_DIRECTORY = fileURLToPath(new URL(".", import.meta.url));

/** The tags this generator writes, and nothing else. */
type ExifTags = {
  /** 6 is "rotate 90 degrees clockwise to display", a phone held upright. */
  orientation: number;
  /** `YYYY:MM:DD HH:MM:SS`, the camera's wall clock. */
  dateTimeOriginal: string;
  /** `+HH:MM`, or undefined for a camera that writes no offset. */
  offsetTimeOriginal: string | undefined;
};

/** Runs one tool, and stops the whole script loudly if it fails. */
function _run(command: string, args: readonly string[]): void {
  const result = spawnSync(command, args, { stdio: "inherit" });
  if (result.error !== undefined || result.status !== 0) {
    throw new Error(
      `${command} ${args.join(" ")} failed. This needs magick, ffmpeg and ` +
        "sips: see the comment at the top of this file.",
    );
  }
}

/** One 12-byte IFD entry, big-endian, its value or offset left-justified. */
function _makeIfdEntryFromField(options: {
  tag: number;
  type: number;
  count: number;
  value: Buffer;
}): Buffer {
  const entry = Buffer.alloc(12);
  entry.writeUInt16BE(options.tag, 0);
  entry.writeUInt16BE(options.type, 2);
  entry.writeUInt32BE(options.count, 4);
  options.value.copy(entry, 8);
  return entry;
}

/** A four-byte IFD value: a 16-bit SHORT or a 32-bit LONG, left-justified. */
function _makeIfdValueFromNumber(options: {
  value: number;
  bytes: 2 | 4;
}): Buffer {
  const value = Buffer.alloc(4);
  if (options.bytes === 2) {
    value.writeUInt16BE(options.value, 0);
  } else {
    value.writeUInt32BE(options.value, 0);
  }
  return value;
}

/** Where each string starts, counting on from `firstOffset`. */
function _getOffsetsFromStrings(options: {
  strings: readonly Buffer[];
  firstOffset: number;
}): number[] {
  return options.strings.reduce<number[]>((offsets, _value, index) => {
    const previousOffset = offsets[index - 1];
    const previousLength = options.strings[index - 1]?.length ?? 0;
    return [
      ...offsets,
      previousOffset === undefined
        ? options.firstOffset
        : previousOffset + previousLength,
    ];
  }, []);
}

/** IFD0: Orientation, then the pointer to the Exif IFD. */
function _makeIfd0FromTags(options: {
  orientation: number;
  exifIfdOffset: number;
}): Buffer {
  return Buffer.concat([
    Buffer.from([0x00, 0x02]),
    _makeIfdEntryFromField({
      tag: 0x0112,
      type: 3,
      count: 1,
      value: _makeIfdValueFromNumber({ value: options.orientation, bytes: 2 }),
    }),
    _makeIfdEntryFromField({
      tag: 0x8769,
      type: 4,
      count: 1,
      value: _makeIfdValueFromNumber({
        value: options.exifIfdOffset,
        bytes: 4,
      }),
    }),
    Buffer.alloc(4),
  ]);
}

/** The Exif IFD: DateTimeOriginal, then OffsetTimeOriginal if there is one. */
function _makeExifIfdFromStrings(options: {
  strings: readonly Buffer[];
  offsets: readonly number[];
}): Buffer {
  return Buffer.concat([
    Buffer.from([0x00, options.strings.length]),
    ...options.strings.map((value, index) => {
      return _makeIfdEntryFromField({
        tag: index === 0 ? 0x9003 : 0x9011,
        type: 2,
        count: value.length,
        value: _makeIfdValueFromNumber({
          value: options.offsets[index] ?? 0,
          bytes: 4,
        }),
      });
    }),
    Buffer.alloc(4),
  ]);
}

/**
 * A JPEG `APP1` segment holding IFD0 and an Exif IFD, big-endian.
 *
 * Offsets count from the TIFF header, which starts after `Exif\0\0`: IFD0 at
 * 8, the Exif IFD straight after it, the strings after that. Entries stay in
 * ascending tag order, which TIFF requires.
 */
function _makeExifSegmentFromTags(tags: Readonly<ExifTags>): Buffer {
  const strings = [tags.dateTimeOriginal, tags.offsetTimeOriginal]
    .filter((value): value is string => {
      return value !== undefined;
    })
    .map((value) => {
      return Buffer.from(`${value}\0`, "latin1");
    });
  const exifIfdOffset = 8 + 2 + 2 * 12 + 4;
  const offsets = _getOffsetsFromStrings({
    strings,
    firstOffset: exifIfdOffset + 2 + strings.length * 12 + 4,
  });
  const tiff = Buffer.concat([
    Buffer.from("MM\0*", "latin1"),
    _makeIfdValueFromNumber({ value: 8, bytes: 4 }),
    _makeIfd0FromTags({ orientation: tags.orientation, exifIfdOffset }),
    _makeExifIfdFromStrings({ strings, offsets }),
    ...strings,
  ]);
  const payload = Buffer.concat([Buffer.from("Exif\0\0", "latin1"), tiff]);
  const length = Buffer.alloc(2);
  length.writeUInt16BE(payload.length + 2, 0);
  return Buffer.concat([Buffer.from([0xff, 0xe1]), length, payload]);
}

/** Copies a JPEG with the EXIF segment written straight after its SOI. */
function _writeJpegWithExif(options: {
  sourcePath: string;
  targetPath: string;
  tags: Readonly<ExifTags>;
}): void {
  const jpeg = readFileSync(options.sourcePath);
  writeFileSync(
    options.targetPath,
    Buffer.concat([
      jpeg.subarray(0, 2),
      _makeExifSegmentFromTags(options.tags),
      jpeg.subarray(2),
    ]),
  );
}

/**
 * An upright portrait picture stored on its side, the way a phone stores one.
 *
 * Drawn upright at 1800x2400 with a red band across the top, then turned a
 * quarter counter-clockwise into 2400x1800 pixels. Orientation 6 turns it
 * back, so a viewer that honours the tag shows the band at the top and one
 * that ignores it shows the band down the left.
 */
function _writeSidewaysPortrait(targetPath: string): void {
  _run("magick", [
    "-size",
    "1800x2400",
    "xc:#e8dcc4",
    "-fill",
    "#c0392b",
    "-draw",
    "rectangle 0,0 1799,340",
    "-fill",
    "#2c3e50",
    "-draw",
    "polygon 900,490 560,1120 1240,1120",
    "-fill",
    "#27ae60",
    "-draw",
    "circle 900,1760 900,1500",
    "-rotate",
    "-90",
    "-strip",
    "-quality",
    "80",
    targetPath,
  ]);
}

/** A landscape picture with no metadata at all, as a messaging app saves one. */
function _writeForwardedJpeg(targetPath: string): void {
  _run("magick", [
    "-size",
    "2560x1920",
    "xc:#d5e8d4",
    "-fill",
    "#8e44ad",
    "-draw",
    "rectangle 0,0 2559,280",
    "-fill",
    "#e67e22",
    "-draw",
    "circle 1280,1120 1280,720",
    "-strip",
    "-quality",
    "80",
    targetPath,
  ]);
}

/**
 * Two seconds of FFmpeg's test pattern, with `creation_time` in `mvhd`.
 *
 * `+faststart` puts `moov` before `mdat`, which is where a phone puts it and
 * what lets the browser read `creation_time` from the first few kilobytes.
 */
function _writeClip(options: {
  pattern: "testsrc" | "testsrc2";
  codecArgs: readonly string[];
  creationTime: string;
  targetPath: string;
}): void {
  _run("ffmpeg", [
    "-hide_banner",
    "-loglevel",
    "error",
    "-y",
    "-f",
    "lavfi",
    "-i",
    `${options.pattern}=size=320x240:rate=15:duration=2`,
    ...options.codecArgs,
    "-pix_fmt",
    "yuv420p",
    "-movflags",
    "+faststart",
    "-metadata",
    `creation_time=${options.creationTime}`,
    "-an",
    options.targetPath,
  ]);
}

/** A one-page PDF with a correct cross-reference table, and nothing on it. */
function _makeMinimalPdf(): Buffer {
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] >>",
  ].map((body, index) => {
    return `${index + 1} 0 obj\n${body}\nendobj\n`;
  });
  const header = "%PDF-1.4\n";
  const offsets = _getOffsetsFromStrings({
    strings: objects.map((object) => {
      return Buffer.from(object, "latin1");
    }),
    firstOffset: header.length,
  });
  const xrefOffset = header.length + objects.join("").length;
  const xref = [
    `xref\n0 ${objects.length + 1}\n`,
    "0000000000 65535 f \n",
    ...offsets.map((offset) => {
      return `${String(offset).padStart(10, "0")} 00000 n \n`;
    }),
  ].join("");
  const trailer =
    `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n` +
    `startxref\n${xrefOffset}\n%%EOF\n`;
  return Buffer.from(`${header}${objects.join("")}${xref}${trailer}`, "latin1");
}

/** The two rotated photographs and the forwarded one. */
function _writePhotoFixtures(scratch: string): void {
  const sideways = join(scratch, "sideways.jpg");
  _writeSidewaysPortrait(sideways);
  _writeJpegWithExif({
    sourcePath: sideways,
    targetPath: join(FIXTURE_DIRECTORY, "portrait-orientation-6.jpg"),
    tags: {
      orientation: 6,
      dateTimeOriginal: "2026:05:01 12:41:32",
      offsetTimeOriginal: "+02:00",
    },
  });
  const heicSource = join(scratch, "heic-source.jpg");
  _writeJpegWithExif({
    sourcePath: sideways,
    targetPath: heicSource,
    tags: {
      orientation: 6,
      dateTimeOriginal: "2026:05:02 12:10:05",
      offsetTimeOriginal: undefined,
    },
  });
  // ImageIO keeps the EXIF and writes orientation 6 as `irot` as well, as a
  // phone's own encoder does. Quality 40 keeps it a few kilobytes.
  _run("sips", [
    "-s",
    "format",
    "heic",
    "-s",
    "formatOptions",
    "40",
    heicSource,
    "--out",
    join(FIXTURE_DIRECTORY, "heic-rotated.heic"),
  ]);
  _writeForwardedJpeg(join(FIXTURE_DIRECTORY, "IMG-20260503-WA0001.jpg"));
}

/** The two clips: H.264 in MP4, and HEVC tagged `hvc1` in QuickTime. */
function _writeVideoFixtures(): void {
  _writeClip({
    pattern: "testsrc",
    codecArgs: ["-c:v", "libx264", "-profile:v", "baseline"],
    creationTime: "2026-05-04T12:00:00.000000Z",
    targetPath: join(FIXTURE_DIRECTORY, "h264-clip.mp4"),
  });
  // `hvc1` rather than FFmpeg's default `hev1`, because Safari plays only
  // `hvc1`, and it is the tag an iPhone writes.
  _writeClip({
    pattern: "testsrc2",
    codecArgs: [
      "-c:v",
      "libx265",
      "-x265-params",
      "log-level=error",
      "-tag:v",
      "hvc1",
      "-f",
      "mov",
    ],
    creationTime: "2026-05-05T12:00:00.000000Z",
    targetPath: join(FIXTURE_DIRECTORY, "hevc-clip.mov"),
  });
}

const scratchDirectory = mkdtempSync(join(tmpdir(), "upload-fixtures-"));
try {
  _writePhotoFixtures(scratchDirectory);
  _writeVideoFixtures();
  writeFileSync(join(FIXTURE_DIRECTORY, "not-media.pdf"), _makeMinimalPdf());
} finally {
  rmSync(scratchDirectory, { recursive: true, force: true });
}
