import {
  ADMIN,
  createConfiguredMailHealthApp,
} from "../helpers/createConfiguredMailHealthApp.ts";

import { describe, expect, it } from "vitest";
import { mailHealthResponseSchema } from "@memory-shoebox/shared";
import { runMailQueueOnce } from "../../src/mail/runMailQueueOnce.ts";
import { createOwnedTestApp } from "../helpers/createOwnedTestApp/createOwnedTestApp.ts";
import { createRecordingEmailService } from "../helpers/createRecordingEmailService.ts";
import {
  NOW,
  insertInstanceSetting,
  insertOutboundEmail,
} from "../helpers/seedHelpers/seedHelpers.ts";

const SECRET_CODE = "583719" satisfies string;
const PAYLOAD_FRAGMENT = "private-payload-fragment" satisfies string;
const SYNTHETIC_KEY = "re_synthetic-private-api-key" satisfies string;
function _expectPrivateErrorTextExcluded(payload: string): void {
  expect(payload).not.toContain(SECRET_CODE);
  expect(payload).not.toContain(PAYLOAD_FRAGMENT);
  expect(payload).not.toContain(SYNTHETIC_KEY);
  expect(payload).not.toContain('\\"code\\"');
}

describe("mail health error privacy", () => {
  it("hides malformed sign-in payload excerpts generated by the real worker", async () => {
    const { app, database, close } = await createConfiguredMailHealthApp();
    const emailId = await insertOutboundEmail(database, {
      payload_json: `x${SECRET_CODE}{"code":"${SECRET_CODE}","raw":"${PAYLOAD_FRAGMENT}"}`,
      attempts: 4,
    });
    const summary = await runMailQueueOnce({
      database,
      now: NOW,
      sender: createRecordingEmailService(),
    });
    expect(summary.failedCount).toBe(1);
    const stored = await database
      .selectFrom("outbound_emails")
      .select(["last_error_code", "last_error_message", "payload_json"])
      .where("id", "=", emailId)
      .executeTakeFirstOrThrow();
    expect(stored.last_error_code).toBe("render_failed");
    expect(stored.last_error_message).toContain(SECRET_CODE);
    expect(stored.payload_json).toBe("{}");
    const response = await app.inject("/api/mail/health");
    expect(response.statusCode).toBe(200);
    _expectPrivateErrorTextExcluded(response.payload);
    const health = mailHealthResponseSchema.parse(response.json());
    expect(health.lastError?.code).toBe("render_failed");
    expect(health.lastError?.message).toBeTruthy();
    expect(health.diagnosis).toBeNull();
    await close();
  });

  it("keeps verification diagnosis useful without returning arbitrary provider text", async () => {
    const { app, database, close } = await createConfiguredMailHealthApp();
    await insertOutboundEmail(database, {
      state: "failed",
      last_error_code: "validation_error",
      last_error_message: `Domain not verified: ${SECRET_CODE} ${PAYLOAD_FRAGMENT} ${SYNTHETIC_KEY}`,
    });
    const response = await app.inject("/api/mail/health");
    _expectPrivateErrorTextExcluded(response.payload);
    const health = mailHealthResponseSchema.parse(response.json());
    expect(health.diagnosis?.code).toBe("domain_unverified");
    expect(health.lastError?.code).toBe("validation_error");
    expect(health.lastError?.message).toBeTruthy();
    await close();
  });

  it("normalizes unknown provider identifiers as well as messages", async () => {
    const { app, database, close } = await createConfiguredMailHealthApp();
    await insertOutboundEmail(database, {
      state: "failed",
      last_error_code: SYNTHETIC_KEY,
      last_error_message: `${SECRET_CODE} ${PAYLOAD_FRAGMENT}`,
    });
    const response = await app.inject("/api/mail/health");
    _expectPrivateErrorTextExcluded(response.payload);
    const health = mailHealthResponseSchema.parse(response.json());
    expect(health.lastError?.code).toBe("provider_rejected");
    expect(health.diagnosis?.code).toBe("provider_rejecting");
    await close();
  });

  it("normalizes preexisting domain-check text without overwriting stored facts", async () => {
    const testApp = await createOwnedTestApp({
      authenticate: async () => {
        return ADMIN;
      },
      mailDomainReader: "none",
    });
    await insertInstanceSetting(testApp.database, {
      key: "public.base_url",
      value: "https://family.example.com",
    });
    await insertInstanceSetting(testApp.database, {
      key: "mail.from_address",
      value: "photos@example.com",
    });
    const rawError = `${SECRET_CODE} ${PAYLOAD_FRAGMENT} ${SYNTHETIC_KEY}`;
    await insertInstanceSetting(testApp.database, {
      key: "mail.domain_last_check_error",
      value: rawError,
    });
    const response = await testApp.app.inject("/api/mail/health");
    _expectPrivateErrorTextExcluded(response.payload);
    const health = mailHealthResponseSchema.parse(response.json());
    expect(health.domainLastCheckError).toBeTruthy();
    expect(health.diagnosis?.code).toBe("domain_unverified");
    const stored = await testApp.database
      .selectFrom("settings")
      .select("value")
      .where("key", "=", "mail.domain_last_check_error")
      .executeTakeFirstOrThrow();
    expect(stored.value).toBe(JSON.stringify(rawError));
    await testApp.close();
  });
});
