/**
 * The API contract shared by the server and the web app.
 *
 * Each endpoint contributes a Zod schema plus the type inferred from it, so
 * there is a single source of truth for every payload crossing the wire. The
 * web app parses responses with the schema; the server annotates its handlers
 * with the type.
 *
 * This file is a barrel and holds no definitions: the contract is large enough
 * that one file would be unreadable, and the import path stays
 * `@memory-shoebox/shared` either way. It is the one barrel
 * `docs/rules/typescript.md` permits, being a shared library package's
 * `index.ts`.
 *
 * **Every name is listed, and `export *` is not used.** The rule against
 * namespace exports has no barrel exception, and it earns its keep here: the
 * list below is the only place that says which module a symbol comes from, and
 * without it a name added to any of the seven files would join this package's
 * public contract without anybody deciding that it should.
 *
 * Both halves may import at runtime. The server runs TypeScript directly
 * through Node's type stripping, and a runtime import from this package has
 * been verified to load under it (`docs/shared.md`).
 */
export {
  createSessionRequestSchema,
  createSessionResponseSchema,
  listMySessionsResponseSchema,
  meDtoSchema,
  meResponseSchema,
  memberRoleSchema,
  normalisedEmailSchema,
  notifyPreferencesSchema,
  requestSignInCodeRequestSchema,
  requestSignInCodeResponseSchema,
  revokeMySessionParamsSchema,
  sessionDtoSchema,
  signInCodeSchema,
  updateMeRequestSchema,
  MEMBER_STATUSES,
  type CreateSessionRequest,
  type CreateSessionResponse,
  type ListMySessionsResponse,
  type MeDto,
  type MemberRole,
  type MemberStatus,
  type MeResponse,
  type NotifyPreferences,
  type RequestSignInCodeRequest,
  type RequestSignInCodeResponse,
  type RevokeMySessionParams,
  type SessionDto,
  type UpdateMeRequest,
} from "./auth.ts";
export {
  collectionSchema,
  cursorSchema,
  type CollectionShape,
} from "./collectionSchema.ts";
export {
  createCommentRequestSchema,
  setReactionRequestSchema,
  updateCommentRequestSchema,
  type CreateCommentRequest,
  type SetReactionRequest,
  type UpdateCommentRequest,
} from "./comments.ts";
export {
  burstSummarySchema,
  calendarDateSchema,
  commentDtoSchema,
  idSchema,
  itemSummarySchema,
  mediaRefSchema,
  mediaSourceSchema,
  memberRefSchema,
  milestoneRefSchema,
  personRefSchema,
  reactionKindSchema,
  reactionSummarySchema,
  signedUrlSchema,
  tagRefSchema,
  timestampSchema,
  visibilityRuleIdSchema,
  visibilitySummarySchema,
  type BurstSummary,
  type CommentDto,
  type ItemSummary,
  type MediaRef,
  type MediaSource,
  type MemberRef,
  type MilestoneRef,
  type PersonRef,
  type ReactionKind,
  type ReactionSummary,
  type TagRef,
  type VisibilitySummary,
} from "./dtos.ts";
export {
  commentEmailPayloadSchema,
  emailCommonSchema,
  mailQueueHealthSchema,
  outboundEmailKindSchema,
  outboundEmailTriggerKindSchema,
  OUTBOUND_EMAIL_KINDS,
  OUTBOUND_EMAIL_STATES,
  signInCodeEmailPayloadSchema,
  uploadSessionEmailPayloadSchema,
  type CommentEmailPayload,
  type EmailCommon,
  type EnqueueEmailInput,
  type MailQueueHealth,
  type OutboundEmailKind,
  type OutboundEmailState,
  type OutboundEmailTriggerKind,
  type SignInCodeEmailPayload,
  type UploadSessionEmailPayload,
} from "./email.ts";
export {
  apiErrorDetailsSchema,
  apiErrorSchema,
  type ApiError,
  type ApiErrorDetails,
} from "./errors.ts";
export { healthResponseSchema, type HealthResponse } from "./health.ts";
export {
  personInputSchema,
  resolveVisibilityRuleRequestSchema,
  resolveVisibilityRuleResponseSchema,
  setCaptureDateRequestSchema,
  setItemPeopleRequestSchema,
  setItemsVisibilityRequestSchema,
  setItemsVisibilityResponseSchema,
  setItemTagsRequestSchema,
  setItemVisibilityRequestSchema,
  updateItemRequestSchema,
  type PersonInput,
  type ResolveVisibilityRuleRequest,
  type ResolveVisibilityRuleResponse,
  type SetCaptureDateRequest,
  type SetItemPeopleRequest,
  type SetItemsVisibilityRequest,
  type SetItemsVisibilityResponse,
  type SetItemTagsRequest,
  type SetItemVisibilityRequest,
  type UpdateItemRequest,
} from "./itemEdits.ts";
export {
  attachedMilestoneSchema,
  burstFrameRefSchema,
  burstFramesRequestSchema,
  burstFramesResponseSchema,
  burstIdParamsSchema,
  commentIdParamsSchema,
  itemCapabilitiesSchema,
  itemDetailSchema,
  itemIdParamsSchema,
  itemsSeenRequestSchema,
  CAPTURE_SOURCES,
  ITEM_ERROR_CODES,
  REACTION_ORDER,
  type AttachedMilestone,
  type BurstFrameRef,
  type BurstFramesRequest,
  type BurstFramesResponse,
  type ItemCapabilities,
  type ItemDetail,
  type ItemsErrorCode,
  type ItemsSeenRequest,
} from "./items.ts";
export { LIMITS, UPLOAD_LIMITS } from "./limits.ts";
export {
  getSettingValueFromStoredValue,
  ianaTimezoneSchema,
  isValidSettingKey,
  publicSettingsResponseSchema,
  PUBLIC_SETTING_KEYS,
  SETTING_DEFINITIONS,
  SETTING_KEYS,
  shellSettingsSchema,
  type PublicSettingsResponse,
  type SettingDefinition,
  type SettingKey,
  type SettingValue,
  type ShellSettings,
} from "./settings.ts";
export {
  dayMilestoneBandSchema,
  dayMilestoneStripSchema,
  filterFacetsRequestSchema,
  filterFacetsResponseSchema,
  personFacetSchema,
  railDaySchema,
  tagFacetSchema,
  timelineDaySchema,
  timelineFilterQuerySchema,
  timelineRailRequestSchema,
  timelineRailResponseSchema,
  timelineRequestSchema,
  timelineResponseSchema,
  type DayMilestoneBand,
  type DayMilestoneStrip,
  type FilterFacetsRequest,
  type FilterFacetsResponse,
  type PersonFacet,
  type RailDay,
  type TagFacet,
  type TimelineDay,
  type TimelineRailRequest,
  type TimelineRailResponse,
  type TimelineRequest,
  type TimelineResponse,
} from "./timeline.ts";
export {
  captureSourceSchema,
  commitUploadSessionRequestSchema,
  completeUploadFileRequestSchema,
  completeUploadFileResponseSchema,
  createUploadEditRequestSchema,
  manifestCaptureEvidenceSchema,
  manifestEntrySchema,
  manifestOutcomeSchema,
  openUploadSessionRequestSchema,
  pendingFileRefSchema,
  presignMultipartSchema,
  presignSingleSchema,
  presignUploadFileRequestSchema,
  presignUploadFileResponseSchema,
  putUploadManifestRequestSchema,
  putUploadManifestResponseSchema,
  renditionPurposeSchema,
  retryUploadFileResponseSchema,
  setUploadVisibilityRequestSchema,
  uploadBatchEditDtoSchema,
  uploadDayGroupSchema,
  uploadedRenditionSchema,
  uploadEditKindSchema,
  uploadEditParamsSchema,
  uploadFileDtoSchema,
  uploadFileParamsSchema,
  uploadFileStateSchema,
  uploadMismatchGroupSchema,
  uploadOutcomeSummarySchema,
  uploadProblemCodeSchema,
  uploadProgressSchema,
  uploadSessionDetailQuerySchema,
  uploadSessionDetailSchema,
  uploadSessionParamsSchema,
  uploadSessionStateSchema,
  uploadSessionSummarySchema,
  uploadUndatedGroupSchema,
  visibilitySubjectInputSchema,
  RENDITION_PURPOSES,
  UPLOAD_EDIT_KINDS,
  UPLOAD_ERROR_CODES,
  UPLOAD_FILE_STATES,
  UPLOAD_PROBLEM_CODES,
  UPLOAD_SESSION_STATES,
  type CaptureSource,
  type CommitUploadSessionRequest,
  type CompleteUploadFileRequest,
  type CompleteUploadFileResponse,
  type CreateUploadEditRequest,
  type ManifestCaptureEvidence,
  type ManifestEntry,
  type ManifestOutcome,
  type OpenUploadSessionRequest,
  type PendingFileRef,
  type PresignMultipart,
  type PresignSingle,
  type PresignUploadFileRequest,
  type PresignUploadFileResponse,
  type PutUploadManifestRequest,
  type PutUploadManifestResponse,
  type RenditionPurpose,
  type RetryUploadFileResponse,
  type SetUploadVisibilityRequest,
  type UploadBatchEditDto,
  type UploadDayGroup,
  type UploadedRendition,
  type UploadEditKind,
  type UploadEditParams,
  type UploadErrorCode,
  type UploadFileDto,
  type UploadFileParams,
  type UploadFileState,
  type UploadMismatchGroup,
  type UploadOutcomeSummary,
  type UploadProblemCode,
  type UploadProgress,
  type UploadSessionDetail,
  type UploadSessionDetailQuery,
  type UploadSessionParams,
  type UploadSessionState,
  type UploadSessionSummary,
  type UploadUndatedGroup,
  type VisibilitySubjectInput,
} from "./upload.ts";
export {
  directoryPersonSchema,
  peopleRequestSchema,
  peopleResponseSchema,
  tagCountSchema,
  tagsRequestSchema,
  tagsResponseSchema,
  type DirectoryPerson,
  type PeopleRequest,
  type PeopleResponse,
  type TagCount,
  type TagsRequest,
  type TagsResponse,
} from "./vocabularies.ts";
