import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { z } from "zod";

function _makeExportDeclarationFromGroup(
  group: Readonly<{ module: string; values: string[]; types: string[] }>,
): string {
  const names = [
    ...group.values.map((name) => {
      return `  ${name},`;
    }),
    ...group.types.map((name) => {
      return `  type ${name},`;
    }),
  ];
  return `export {\n${names.join("\n")}\n} from "${group.module}";`;
}

/** Generates or checks the shared package's public export allowlist. */
export function generateSharedExports(): void {
  const manifestPath = new URL("./sharedExports.json", import.meta.url);
  const outputPath = new URL("../src/index.ts", import.meta.url);
  const groups = z
    .array(
      z.strictObject({
        module: z.string().regex(/^\.\/.*\.ts$/),
        values: z.array(z.string()),
        types: z.array(z.string()),
      }),
    )
    .parse(JSON.parse(readFileSync(manifestPath, "utf8")));
  const names = groups.flatMap((group) => {
    return [...group.values, ...group.types];
  });
  if (new Set(names).size !== names.length) {
    throw new Error("The shared export allowlist contains duplicate names.");
  }
  const header =
    "/**\n * Generated by scripts/generateSharedExports.ts from sharedExports.json.\n * Edit the allowlist and run pnpm generate:exports; do not edit this file.\n * The explicit API remains erasable TypeScript for Node runtime imports.\n */\n";
  const output = execFileSync(
    "oxfmt",
    ["--stdin-filepath", fileURLToPath(outputPath)],
    {
      input: `${header}${groups.map(_makeExportDeclarationFromGroup).join("\n")}\n`,
      encoding: "utf8",
    },
  );
  if (process.argv.includes("--check")) {
    if (readFileSync(outputPath, "utf8") !== output) {
      throw new Error(
        `Regenerate ${fileURLToPath(outputPath)} with pnpm generate:exports.`,
      );
    }
    return;
  }
  writeFileSync(outputPath, output);
}

generateSharedExports();
